### PR TITLE
adding sona id entry task to library

### PR DESCRIPTION
**Pull request by danieljwilson**

### CODE REVIEW

**Comment by vsoch** [comment]
Looks like you need to turn on GitHub pages so the experiment appears here: https://danieljwilson.github.io/sona-id-entry/

**Comment by danieljwilson** [comment]
Hm, I thought that I had turned it on but maybe I did something incorrectly?

image

**Comment by danieljwilson** [comment]
Getting this message on the main repo page as well:
image

**Comment by vsoch** [comment]
Yep it looks like pages is having issues - not your fault! https://github.com/danieljwilson/sona-id-entry/actions/runs/2021835803 And probably everyone is sleeping so it's not a thing on the status board yet. Let's keep trying every few hours or so (and I'll watch the repo) and re-run when pages is working again.

**Comment by danieljwilson** [comment]
Okay sounds good!

**Comment by vsoch** [comment]
Do you want to try restarting it to see if it works? https://github.com/danieljwilson/sona-id-entry/actions/runs/2021844807

**Comment by danieljwilson** [comment]
Hm, seems like it is pending/queuing?

image

**Comment by danieljwilson** [comment]
Okay, working now!!

**Comment by vsoch** [comment]
yep and I triggered a re-run - fingers crossed!

**Comment by vsoch** [comment]
I don't see an issue for why the CI is failing because the URL works for me - going to pull and test locally.

**Comment by danieljwilson** [comment]
👍

**Comment by vsoch** [comment]
Ah so the issue is your config validation - this needs to be a list https://github.com/danieljwilson/sona-id-entry/blob/a3b03b24462149169eaec9acbddf445ff8167135/config.json#L12

**Comment by danieljwilson** [comment]
Ahhh...lol, I thought that if I was only giving one URL then I didn't need to make it a list, whoops! Changing it right now!

**Comment by danieljwilson** [comment]
I think this is working now? Fixed the `.config` file...
https://github.com/danieljwilson/sona-id-entry/blob/master/config.json#:~:text=%22reference%22%3A%20%5B,%5D%2C

**Pull request merged**
