### PR TITLE
Add consent-task to library.

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by vsoch** [comment]
See https://github.com/earcanal/consent-task/issues/1 - it looks like just the logo is missing!

This is a super idea, I'm so glad you are contributing it!

**Comment by vsoch** [comment]
oh crap we are running on Circle 1.0! Let me see if I can work to fix that for this PR. It's going to be deprecated very soon.

**Comment by vsoch** [comment]
huh, that's really weird - I did the update already :/ I wonder if it's a bug in circle? Let me file it.

**Comment by vsoch** [comment]
hey @earcanal the reason for the error message is because your branch (where the PR is being submit from) still has the old circle.yml (note that this one has a folder called .circleci). Could you please update your branch with the master here to retrigger testing on the correct framework? Thanks!

**Comment by earcanal** [comment]
I did `git fetch upstream` in my fork but nothing changed :-/

**Comment by earcanal** [comment]
Duh!  Need to `merge` also.

**Comment by vsoch** [comment]
it looks like the patch url isn't defined, which is where we get a history of builds. This might be because I cleared the cache, I'm looking into it now.

**Comment by vsoch** [comment]
Yeah I think that's it! The compare url is blank!
```bash
$ env | grep CIRCLE
CIRCLE_NODE_INDEX=0
CIRCLE_BUILD_URL=https://circleci.com/gh/expfactory/experiments/159
CIRCLE_COMPARE_URL=
```

Thankfully this is literally a "will happen once and never again" thing, granted that the cache isn't again cleared. Still, I'm going to put in a check for an empty variable, and if found, proceed with testing all the containers. This is what would be needed anyway given that someone decided to start a completely new repo, so it shouldn't bug out.

**Comment by earcanal** [comment]
OK!

**Comment by vsoch** [comment]
hey @earcanal can you do the same again - update your experiments repo with the version now fixed at expfactory/experiments? My fingers are crossed that this should work now, or be a bit closer to working :)

**Comment by vsoch** [comment]
okay it's actually working, and it's going to take a bit because it's testing ALL the repos, haha. But this should be good - we will see if there are any missing / errored experiment repos!

**Comment by vsoch** [comment]
Looks good!

```bash
TESTING /home/circleci/experiments/docs/_library/consent-task.md
layout: experiment
name: consent-task
maintainer: @earcanal
github: https://github.com/earcanal/consent-task
preview: https://earcanal.github.io/consent-task
tags: ['consent', 'debrief', 'jspsych', 'experiment']
Cloning into '/tmp/tmpk385otin/consent-task'...
remote: Counting objects: 367, done.        
remote: Compressing objects: 100% (274/274), done.        
remote: Total 367 (delta 94), reused 353 (delta 80), pack-reused 0        
Receiving objects: 100% (367/367), 4.45 MiB | 0 bytes/s, done.
Resolving deltas: 100% (94/94), done.
Cloning into '/tmp/tmp_564wgzh/consent-task'...
remote: Counting objects: 367, done.        
remote: Compressing objects: 100% (274/274), done.        
remote: Total 367 (delta 94), reused 353 (delta 80), pack-reused 0        
Receiving objects: 100% (367/367), 4.45 MiB | 0 bytes/s, done.
Resolving deltas: 100% (94/94), done.
.../tmp/tmp_564wgzh/consent-task/consent.css
.../tmp/tmp_564wgzh/consent-task/experimental.html
.../tmp/tmp_564wgzh/consent-task/index.html
WARNING LICENSE file not found. This will be required for future experiments!
True
https://github.com/earcanal/consent-task
```
Are you done with changes on the experiment branch? If so, I'll merge when you are ready and give the OK.

**Comment by earcanal** [comment]
I'm done with `add/consent-task`.  Is that the branch you mean?

**Comment by vsoch** [comment]
Yes! In that case, the tests pass here, so ready for merge!

**Comment by earcanal** [comment]
Done (I think)!

**Comment by vsoch** [comment]
Woot! Great job, and thanks for the new experiment!

**Pull request merged**
