### PR TITLE
Add zoning out task to library.

### PR DESCRIPTION
**Pull request by earcanal**
My first contribution to the library.  Let's hope I RTFM correctly.

### CODE REVIEW

**Comment by vsoch** [comment]
Cool! I just tried it in your Github pages (have you tried it?) I click the next button in the upper left, then submit, and it's over. Is that how it's supposed to work?

**Comment by earcanal** [comment]
No, but that's the problem I had when running statically.  It uses `$.ajax` to present the content so that might explain this fail?

**Comment by vsoch** [comment]
You are missing jquery 
image

**Comment by vsoch** [comment]
You can look in the console for errors to debug

**Comment by vsoch** [comment]
oh sorry not that file itself, but something it's calling?

**Comment by earcanal** [comment]
It's in `index.html` (`<script src='js/jquery.min.js'></script>`) and in the repo.  Works locally under `python3 -m http.server 9999`.

**Comment by vsoch** [comment]
ah try changing this:

```
$.ajax({
      url : '/text/' + i + '.html',
      cache: false,
      async: false,
      success : function(result) {
          pages.push(result);
      }
  });
```
to this?

```
$.ajax({
      url : 'text/' + i + '.html',
      cache: false,
      async: false,
      success : function(result) {
          pages.push(result);
      }
  });
```

**Comment by vsoch** [comment]
If you hard code the server base (/) then it would look for that file at `earcanal.github.io/text` instead of `earcanal.github.io/zoning-out-task/text`

**Comment by earcanal** [comment]
Pushed.  Do I need to do anything else, or will it pull and retest?

**Comment by vsoch** [comment]
okay, the preview is working now! A quick suggestion - you might want to put the preview link https://earcanal.github.io/zoning-out-task/ in the repository description (or next to it) so it can be easily found, here:

image

if you edit that, there should be a nice box to the right for it.

Yes, the CI will run tests again.

**Comment by vsoch** [comment]
Looks like your config.json isn't valid json:

```
zoning-out-task: cannot load json, invalid.
F
======================================================================
FAIL: test_experiment (tests.test_library.TestLibrary)
test an experiment, including the markdown file, and repo itself
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/experiments/tests/test_library.py", line 80, in test_experiment
    self.assertTrue(self.ExpValidator.validate(url))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 2.194s

FAILED (failures=1)
```

**Comment by earcanal** [comment]
Thanks for previous fix.  This is working well!

**Comment by vsoch** [comment]
You can't have hanging commas in a list:

```
 "contributors": [
        "Paul Sharpe",
    ],
```
should be the same without the comma after your name

**Comment by vsoch** [comment]
```
In [10]: stringy='''{
    ...:     "name": "Zoning Out Task",
    ...:     "exp_id": "zoning-out-task",
    ...:     "url": "https://www.github.com/earcanal/zoning-out-task",
    ...:     "description": "Read and answer question on chapter 1 of 'War and Peace'.",
    ...:     "instructions": "Hmmm",
    ...:     "template":"jspsych",
    ...:     "contributors": ["Paul Sharpe"],
    ...:     "time": 15,
    ...:     "reference": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2724753/"]
    ...: }'''

In [11]: stringy[311]
Out[11]: '1'

In [12]: json.loads(stringy)
Out[12]: 
{'contributors': ['Paul Sharpe'],
 'description': "Read and answer question on chapter 1 of 'War and Peace'.",
 'exp_id': 'zoning-out-task',
 'instructions': 'Hmmm',
 'name': 'Zoning Out Task',
 'reference': ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2724753/'],
 'template': 'jspsych',
 'time': 15,
 'url': 'https://www.github.com/earcanal/zoning-out-task'}
```

**Comment by earcanal** [comment]
I know, I know.  Fixed.  Pushed.

:)

**Comment by vsoch** [comment]
haha ok :)

**Comment by earcanal** [comment]
Are we waiting for the tests to run again?

**Comment by earcanal** [comment]
I can't tell whether this is the pre-fix test:

```
zoning-out-task: cannot load json, invalid.
F
======================================================================
FAIL: test_experiment (tests.test_library.TestLibrary)
test an experiment, including the markdown file, and repo itself
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/experiments/tests/test_library.py", line 80, in test_experiment
    self.assertTrue(self.ExpValidator.validate(url))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 2.194s
```

**Comment by earcanal** [comment]
Ha ha.  I passed the test(s)!

**Comment by vsoch** [comment]
Woohoo good job! See everything comes down to like, commas and slashes :) Let's add this guy to the library.

**Comment by earcanal** [comment]
Do I have to wait for it to be merged before I can build it into a container?

**Comment by earcanal** [comment]
BOOM!

**Comment by vsoch** [comment]
yeah!! 
zoning

Don't forget to add the preview url in your repo, in case someone wanders there first :)

**Comment by earcanal** [comment]
ZOMG!  (yeah, I updated `README.md`).

**Pull request merged**
