### PR TITLE
Create flanker-children.md

### PR DESCRIPTION
**Pull request by willwade**
Adding flanker for children. Hope this is ok! First attempt at this. Very simple modification taken from the flanker experiment - this time with fish! I'm not sure if I'm doing this right - I'm not liking the stimulus column in the csv but this does the job for us for now.

### CODE REVIEW

**Comment by vsoch** [comment]
hey @willwade it looks like you are almost there! You just need to enable Github pages for your experiment repo, here is the error message from the tester:

```
ERROR Preview not found at https://ACECentre.github.io/flanker-children. You must publish a static 
                         preview from the master branch of your repository to
                         add to the library.
False
https://github.com/ACECentre/flanker-children
F
======================================================================
FAIL: test_experiment (tests.test_library.TestLibrary)
test an experiment, including the markdown file, and repo itself
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/experiments/tests/test_library.py", line 111, in test_experiment
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 30.968s

FAILED (failures=1)

cd $HOME/experiments && $HOME/miniconda3/bin/python -m unittest tests.test_library returned exit code 1
```
I realize I'm not honoring the preview metadata in the config file, and I can definitely adjust the test to do this. But ideally, we would serve the preview from the same Github folder (so updates to it will update the preview respectively). Are you able to turn on Github pages and have it render from master?

I'm very much looking forward to seeing the fish! :)

**Comment by willwade** [comment]
Ok. Hopefully fixed!

**Comment by vsoch** [comment]
I will test this locally - it does look like you have Github pages at ACECentre.github.io/flanker-children but the CI isn't detecting it. It might be something trivial like capitalization. I will report back!

**Comment by vsoch** [comment]
woohoo! It was actually fixed, I just needed to run the tests :) Merging!

**Pull request merged**
