### PR TITLE
Add RSVP task to library.

### PR DESCRIPTION
**Pull request by earcanal**
This has had some pilot testing, so should be good to go.

### CODE REVIEW

**Comment by vsoch** [comment]
I should update the CI for sure.

For the task, I don't quite understand it. Does it say "Press a number key" and then "Press another number key indefinitely?"

**Comment by earcanal** [comment]
If it's working correctly you give 2 responses, one for the first number you saw and one for the second.  You keep doing this for the total number of trials.

**Comment by vsoch** [comment]
The first number of what? I think I didn't read the instructions well, haha.

**Comment by earcanal** [comment]
I'd be interested to know if it makes sense after you've read the instructions.  That worked for my pilot participants!

**Comment by vsoch** [comment]
haha no don't worry, this is definitely a user error - I'm the one that gets a new thing, tears it apart, and proceeds to put it together... without reading a word :)

I'll be able to finish updating the CI later today, then test, then we can test against this experiment (and merge). I'd like to also try setting up testing on the level of the experiment, if you are interested I can help with that. If not, I can do for another experiment and then show you how.

**Comment by vsoch** [comment]
Just a heads up @earcanal circle is having some down-ish struggles, so we can pick up when their robots are healthy again!

**Comment by vsoch** [comment]
ok, resuming testing the CI!

**Comment by vsoch** [comment]
hey @earcanal ! The new testing is in place, so please update / do some trivial change so that it triggers again.

**Comment by vsoch** [comment]
okay it's running!! :D

**Comment by vsoch** [comment]
I'm just going to merge and cross my fingers, it's likely a circle bloop.

**Pull request merged**
